# Generated by Django 3.2.9 on 2021-12-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_tag_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user',
        ),
    ]
