# Generated by Django 3.2.9 on 2021-12-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, default='SEO', to='post.Tag'),
        ),
    ]
